---
always_allow_html: true
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
source(here::here("figures_tables", "_common.R"))
```

```{r}
tbl <- {{table.num.to.print}}
csvfile <- paste0("{{data_id}}", ".csv")
datafile <- here::here("data", csvfile)
counts <- read.csv(datafile, stringsAsFactors=FALSE)
modtime <- system(paste("git log -1 --format=%cd", datafil), intern=TRUE)
```

<!-- fixcols is in _common.R
     A function I need for data wrangling. There are better ways to do this -->

```{r}
colnames(counts) <- fixcols(colnames(counts))
```


```{r}
popname <- unique(counts$`Common Population Name`)[tbl]
dat <- subset(counts, `Common Population Name`==popname & Year >= {{startYr}})
rownames(dat) <- c()
tbl_cap <- paste0("Spawners and fracwild from ", popname, " for ", min(dat$Year), " to ", max(dat$Year), ". ")
```

<!-- unlike tbl-cap, label won't take a string so !expr tbl_label won't work. But you can still make this work with the hack below. -->

```{r results='asis'}
if(isword) cat("\n", wordnewpage, "\n")
if(ispdf) cat("\n\\newpage\n\n")
cat("### ", popname, "\n\n")

```

<!-- tablecount function -->
```{r}
tablecount <- function(data, cols="Spawners"){
  dat <- data[, c("Year", cols)]
  f1 <- paste("** data file:", csvfile, "mod date:", modtime)
  f2 <- "* These spawner counts are from river redd surveys."
  if(table.engine=="flextable"){
    tab <- dat %>%
      myflextable() %>%
      autofit() %>%
      add_footer(., Year = f2) %>%
      merge_at(., i = 1, j = 1:ncol(dat), part = "footer") %>% 
      add_footer(., Year = f1) %>%
      merge_at(., i = 1, j = 1:ncol(dat), part = "footer") %>% 
      colformat_num(., j=1, big.mark = "", na_str = "NA")
    # %>% line_spacing(space = 1.0, part = "all")
  }
  if(table.engine=="kbl"){
    tab <- 
      dat %>%
      mykbl() %>%
      kableExtra::add_footnote(c(f1, f2), notation="none") %>%
      kableExtra::kable_styling(latex_options = c( "HOLD_position"))
  }
  tab
}
```

```{r}
#| label: tbl-raw{{data_id}}{{table.num.to.print}}
#| tbl-cap: !expr tbl_cap
out <- NULL
col <- c("Spawners", "Fracwild")
if(nrow(dat) > 0){
  tab <- tablecount(dat, cols=col)
}else{
  tab <- paste("No data for years greater than or equal to", {{startYr}})
}
tab
```

```{r results='asis'}
if(isword) cat("\n", wordnewpage, "\n")
if(ispdf) cat("\n\\newpage\n\n")
```
