---
title: "Raw Data Tables"
---

<!-- Since the main file (index) had this, I don't need to repeat it. 
     But I do so that I can run this Rmd independently during debugging and development.
     I set all the output to FALSE. -->
     
```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
source(here::here("figures_tables", "_common.R"))
```

```{r}
startYr <- 2000
```

```{r}
# So that I can later have many cvsfiles
datafil <- here::here("data", paste0(data_id, ".csv"))
tmp <- read.csv(datafil, stringsAsFactors=FALSE)
ntbl <- tmp %>% distinct(COMMON_POPULATION_NAME) %>% nrow()
```

```{r include=FALSE}
# This is cycling through all the populations in the data
# this is a big hacky because I can't use variables in `label: `
# So I am having to create popid here so I can use {{popid}} in the label
out <- NULL
for(table.num.to.print in 1:ntbl){
  popname <- unique(tmp$`COMMON_POPULATION_NAME`)[table.num.to.print]
  tmp2 <- subset(tmp, `COMMON_POPULATION_NAME`==popname)
  popid <- unique(tmp2$NMFS_POPID)[1]
  out = c(out, knit_expand(here::here('figures_tables', '_template_raw_table.Rmd')))
}
```
`r paste(knit(text = out), collapse = '\n')`

