---
title: "Table of Population Counts"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
---

```{r include=FALSE}
# Since the master had this, I don't need to repeat it. But I do so that I can
# run this Rmd independently during debugging and development
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(knitr)
# need this for %>% function and nice html tables
library(kableExtra)
# need to know the format
ishtml <- knitr::is_html_output()
ispdf <- knitr::is_latex_output()
isword <- !ishtml & !ispdf
```

```{r}
fixcols <- function(x){
  # fix _ and . in colname and make title format
  x <- stringr::str_replace_all(x, "_", " ")
  x <- stringr::str_replace_all(x, "[,]", " ")
  x <- stringr::str_to_title(x)
  x[x=="Esu"] <- "ESU"
  x[x=="Number Of Spawners"] <- "Spawners"
  x
}
```

<!-- This is how to get a new page in Word. Make sure you are in print view on the word doc -->

```{r}
wordnewpage <-
'```{=openxml}
<w:p><w:r><w:br w:type="page"/></w:r></w:p>
```'
```

```{r}
fil <- "Lower_Columbia_River_Chinook.csv"
filful <- file.path(here::here(), "data", fil)
modtime <- system(paste("git log -1 --format=%cd", filful), intern=TRUE)
counts <- read.csv(filful, stringsAsFactors=FALSE)
colnames(counts) <- fixcols(colnames(counts))
```

```{r}
# Create my table function; set default cols but different cols can be passed in
tablecount <- function(data, cols="Spawners", caption=""){
  dt <- data[, c("Year", cols)]
  algn <- paste0("l", paste(rep("c", ncol(dt)-1), collapse=""))
  cap <- paste0(caption, "Yearly counts of ", paste(cols, collapse=" and "), " for ", min(dt$Year), " to ", max(dt$Year))
  if(isword)
  tab <- knitr::kable(dt, align=algn, caption=cap, digits=0, 
               row.names=FALSE, format="pandoc")
  if(ishtml){
     tab <- dt %>% 
       kableExtra::kbl(align=algn, caption=cap, digits=0, row.names=FALSE) %>% 
       kableExtra::kable_styling(full_width = FALSE) %>%
       add_footnote(paste("data file date:", modtime))
  }
  tab
}
```

```{r results='asis', eval=isword}
tbl <- 2
col <- c("Spawners", "Fracwild")
for(i in unique(counts$`Common Population Name`)[1:tbl]){
  dat <- subset(counts, `Common Population Name`==i & Year %in% 2000:2014)
  cap <- paste0("Table ", tbl, ". ", i, ". ")
  tab <- tablecount(dat, cols=col, caption=cap)
  cat("\n", wordnewpage, "\n")
  print(tab)
  tbl <- tbl + 1
}
```

```{r results='asis', eval=ishtml}
tbl <- 2
col <- c("Spawners", "Fracwild")
for(i in unique(counts$`Common Population Name`)[1:tbl]){
  dat <- subset(counts, `Common Population Name`==i & Year %in% 2000:2014)
  cap <- paste0("Table ", tbl, ". ", i, ". ")
  tab <- tablecount(dat, cols=col, caption=cap)
  print(tab)
  tbl <- tbl + 1
}
```

