---
title: "Table in For Loop"
---

<!-- Since the main file (index) had this, I don't need to repeat it. 
     But I do so that I can run this Rmd independently during debugging and development.
     I set all the output to FALSE. -->
     
```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
library(knitr)
library(dplyr) # need this for %>% function
library(flextable)
library(xtable)
```


<!-- Outputting the table as markdown.
     Note the cat(knitr::knit_print(tab))
     This is done this way so that it is cross-compatible 
     with PDF, HTML and Word. -->


```{r}
  data(tli)
  fm3 <- glm(disadvg ~ ethnicty*grade, data = tli, family = binomial)
  ft <- flextable::xtable_to_flextable(xtable::xtable(anova(fm3)), hline.after = c(1))
  ft <- ft %>%
    font(fontname="Times New Roman", part="all") %>%
    fontsize(size=12)
```


```{r results='asis'}
for(i in 1:3){
  ft <- set_caption(ft, 
  caption = paste("Flextable table in a for loop", i), 
  style = "Table Caption")
  cat(knitr::knit_print(ft))
}
```
